### ISSUE TITLE
User add does not specify the user nor group ID

### ISSUE THREAD

**Issue by svyotov** [bitnami/minideb-extras#687]
Hi!
I noticed that the user creation is not explicitly specifying the user ID, which in this case is 1000.
To my understanding this will cause issues in cases such as this https://github.com/bitnami/bitnami-docker-postgresql/blob/5b9108b19cee7549621442214571585bcdbc345c/10/debian-9/Dockerfile#L40, where a non existing user id is beingused.
Relevant line of code:
https://github.com/bitnami/minideb-extras/blob/448d145213456b2a4ce9e475c8dc198e7731a4f4/stretch/Dockerfile#L9
Thank you!

**Comment by marcosbc** [comment]
Actually the user "bitnami" doesn't have anything to do with user 1001 being used in Bitnami Docker images, and that's intentional.

The reasoning behind this is that images are more secure this way, as it avoids the possibility of escalating privileges with tools such as "su" or "sudo". E.g.:

```
I have no name!@570f2cdf0c9a:/$ su root
su: Cannot determine your user name.
I have no name!@570f2cdf0c9a:/$ sudo su root
sudo: unknown uid 1001: who are you?
```
